    [tool.ruff]
    line-length = 120
    select = ["E", "F", "W", "I"] # Example: enable error, flake8-style, warning, and import sorting rules
    #ignore = ["E501"] # Example: ignore line length errors
